# Generated by Django 4.1.7 on 2023-06-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('event_status', models.CharField(choices=[('CREATED', 'created'), ('INPROGRESS', 'in_progress'), ('FINISHED', 'finished')], max_length=20)),
                ('attendees', models.IntegerField(default=0)),
                ('event_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
